---
title: "Análisis de Sangre Matteo"
format: html
editor: visual
---

## **ANÁLISIS DE SANGRE 18-05-2023**

-   TRANSAMINASA PIRUVICA (GPT) 25.4 U/L Intervalo de referencia (MENOR DE 50 U/L)

-   MONOTEST (Mononucleosis Infecciosa) Negativo\
    METODO: HEMAGLUTINACION

-   CITOMEGALOVIRUS IgM 0.14 ID Intervalo de referencia (NO REACTIVO : MENOR A 0.70 INDETERMINADO: 0.70 A 1.0 REACTIVO: MAYOR A 1.0)

-   PCR Proteina C Reactiva Cuantitativa \* 11.01 mg/L Intervalo de referencia (0.00 - 10.00)

-   EPSTEIN BARR ANTICUERPOS IGM (CAPSULA EB VCA M) 0.15 Intervalo de referencia (NEGATIVO DE 0.00 A 0.11 DUDOSO DE 0.12 A 0.18 POSITIVO MAYOR O IGUAL A 0.19)

-   RECUENTO DE LEUCOCITOS 13.17 X10³/mm³ Intervalo de referencia (5.50 - 17.00)

-   RECUENTO DE HEMATIES \* 5.28 X10\*6/mm³ Intervalo de referencia (4.60 - 5.10)

-   HEMOGLOBINA 13.70 gr/dl Intervalo de referencia (11.80 - 13.70)

-   HEMATOCRITO 39.7 % Intervalo de referencia (37.0 - 40.0)

-   MCV \* 75.2 fl Intervalo de referencia (76.0 - 84.0)

-   MCH 25.9 pg Intervalo de referencia (25.0 - 29.0)

-   MCHC 34.5 gr/dl Intervalo de referencia (33.0 - 35.0)

-   RECUENTO TOTAL DE PLAQUETAS \* 419 x10\^3/uL Intervalo de referencia (140 - 400)

-   RDW 13.70 % Intervalo de referencia (11.60 - 14.40)

-   MPV \* 9.1 fl Intervalo de referencia (9.4 - 12.4)

-   NEUTROFILOS % \* 61.20 % Intervalo de referencia (30.00 - 39.00)

-   LINFOCITOS % \* 33.10 % Intervalo de referencia (50.00 - 63.00)

-   MONOCITOS % 4.90 % Intervalo de referencia (1.00 - 5.00)

-   EOSINOFILOS % 0.50 % Intervalo de referencia (0.50 - 2.80)

-   BASOFILOS % 0.30 % Intervalo de referencia (0.04 - 0.60)

-   NEUTROFILOS Abs \* 8.06 x10\^3/uL Intervalo de referencia (1.56 - 6.13)

-   LINFOCITOS Abs \* 4.36 x10\^3/uL Intervalo de referencia (1.32 - 3.57)

-   MONOCITOS Abs 0.65 x10\^3/uL Intervalo de referencia (0.00 - 1.90)

-   EOSINOFILOS Abs 0.06 x10\^3/uL Intervalo de referencia (0.00 - 0.40)

-   BASOFILOS Abs 0.04 x10\^3/uL Intervalo de referencia (0.01 - 0.08)

## **Diagnóstico**

**1. TRANSAMINASA PIRUVICA (GPT)**: El nivel de transaminasa pirúvica (GPT) se encuentra dentro del rango normal, lo que sugiere una función hepática adecuada.

**2. MONOTEST (Mononucleosis Infecciosa)**: El resultado es negativo para la mononucleosis infecciosa, lo que indica que no hay evidencia de infección por el virus Epstein Barr, que es la causa común de la enfermedad.

**3. CITOMEGALOVIRUS IgM**: El nivel de anticuerpos IgM para el citomegalovirus se encuentra dentro del rango negativo, lo que sugiere que no hay evidencia de infección aguda por citomegalovirus.

**4. PCR Proteína C Reactiva Cuantitativa**: El nivel de PCR cuantitativa es ligeramente elevado, lo que indica la presencia de una respuesta inflamatoria en el cuerpo. Esto puede ser causado por diversas condiciones, y se requiere una evaluación adicional para determinar la causa subyacente.

**5. EPSTEIN BARR ANTICUERPOS IGM**: El nivel de anticuerpos IgM para el virus Epstein Barr es ligeramente elevado, lo que sugiere una posible infección activa. Sin embargo, se necesita una evaluación clínica más detallada y pruebas adicionales para confirmar el diagnóstico.

**6. CUADRO HEMATICO IV**: En general, los resultados del hemograma indican recuentos de glóbulos blancos, glóbulos rojos y plaquetas dentro del rango de referencia normal. Sin embargo, hay algunas variaciones leves en los valores de MCV, recuento total de plaquetas y MPV, que pueden ser indicativos de pequeñas irregularidades en los glóbulos rojos y plaquetas. Estas variaciones pueden requerir seguimiento y evaluación adicional.

**7. NEUTRÓFILOS % y LINFOCITOS %**: Los niveles de neutrófilos están ligeramente elevados, mientras que los niveles de linfocitos están ligeramente disminuidos en comparación con los rangos de referencia normales. Esto puede ser una respuesta a la infección o inflamación, pero se necesitan más pruebas y una evaluación clínica detallada para determinar la causa subyacente.

## **Conclusiones**

En resumen, estos resultados indican algunas variaciones y hallazgos que pueden requerir seguimiento y evaluación adicional por parte de un médico. Es importante considerar el cuadro clínico completo del niño, incluyendo síntomas y antecedentes médicos, para obtener un diagnóstico preciso y proporcionar el tratamiento adecuado, si es necesario. Se recomienda consultar a al pediatra para una interpretación completa de estos resultados.

------------------------------------------------------------------------

## **ANÁLISIS DE SANGRE 01-20-24**

### **Bioquímica:**

1.  **Urea: 24.8 mg/dl** (intervalo de referencia: 15 - 36)

    -   El valor está dentro del rango normal.

2.  **Nitrogeno Ureico (BUN): 11.6** (intervalo de referencia: 5.0 - 18.0)

    -   El valor está dentro del rango normal.

3.  **Creatinina en suero: 0.40 mg/dl** (intervalo de referencia: 0.29 - 0.47)

    -   El valor está dentro del rango normal.

4.  **Transaminasa Glutámico Oxalacética (GOT): 31.9 U/L** (intervalo de referencia: 5.0 - 52.0)

    -   El valor está dentro del rango normal.

5.  **Transaminasa Glutámico Pirúvica (GPT): 24.4 U/L** (intervalo de referencia: 5.0 - 39.0)

    -   El valor está dentro del rango normal.

6.  **Fosfatasa Alcalina Total: 253.0 U/L** (intervalo de referencia: 142.0 - 335.0)

    -   El valor está dentro del rango normal.

7.  **Creatin Quinasa Total (CK CPK): 220.0 U/L** (intervalo de referencia: 10.0 - 190.0)

    -   **Valor: 220.0 U/L**

        -   Este valor está elevado (intervalo de referencia: 10.0 - 190.0 U/L).

        -   La creatina quinasa (CK CPK) es una enzima que se encuentra en varios tejidos, incluyendo los músculos. Niveles elevados pueden indicar daño muscular.

    -   **Recomendación:**

        -   Dado el aumento de CK CPK, se sugiere realizar un seguimiento y correlacionar este resultado con la historia clínica y la evolución actual del niño.

        -   Se puede considerar la realización de pruebas adicionales, como estudios de imagen o consultas con un especialista en pediatría o neurología para evaluar el origen del aumento de la CK CPK.

8.  **Vitamina B12: 1023.0 pg/ml** (intervalo de referencia: 197.0 - 771.0)

    -   **Valor: 1023.0 pg/ml**

        -   Este valor está elevado (intervalo de referencia: 197.0 - 771.0 pg/ml).

        -   La vitamina B12 es esencial para la formación de glóbulos rojos y el mantenimiento del sistema nervioso. Niveles elevados pueden deberse a varias razones, como suplementación o condiciones médicas específicas.

    -   **Recomendación:**

        -   Se sugiere realizar un seguimiento y correlacionar este resultado con la historia clínica y la evolución del niño.

        -   Si no hay una razón evidente para el aumento (como suplementación), se puede considerar realizar más pruebas para determinar la causa subyacente.

9.  **Vitamina D, 25 OH, Total: 34.9 ng/ml**

    -   Se encuentra en el rango de insuficiencia de vitamina D (20 - 29 ng/mL). Puede requerir atención y posiblemente suplementación.

### **Hematología:**

1.  **Recuento de Leucocitos: 7.35 x10³/mm³** (intervalo de referencia: 5.00 - 14.50)

    -   El valor está dentro del rango normal.

2.  **Recuento de Hematíes: 4.88 x10\^6/mm³** (intervalo de referencia: 4.60 - 5.10)

    -   El valor está dentro del rango normal.

3.  **Hemoglobina: 13.10 gr/dl** (intervalo de referencia: 13.20 - 14.40)

    -   El valor está ligeramente por debajo del rango normal.

4.  **Hematocrito: 37.4%** (intervalo de referencia: 39.0 - 42.0)

    -   El valor está por debajo del rango normal.

5.  **MCV: 76.6 fl** (intervalo de referencia: 75.0 - 87.0)

    -   El valor está ligeramente por debajo del rango normal.

6.  **MCH: 26.8 pg** (intervalo de referencia: 25.0 - 31.0)

    -   El valor está dentro del rango normal.

7.  **MCHC: 35.0 gr/dl** (intervalo de referencia: 33.0 - 35.0)

    -   El valor está en el límite superior del rango normal.

8.  **Recuento Total de Plaquetas: 341 x10\^3/uL** (140 - 400)

    -   El valor está ligeramente por encima del rango normal.

9.  **RDW: 13.80%** (intervalo de referencia: 11.60 - 14.40)

    -   El valor está dentro del rango normal.

### **Hematología (porcentajes y absolutos):**

1.  **Neutrófilos %: 30.10%** (intervalo de referencia: 46.00 - 55.00)

    -   El valor está por debajo del rango normal.

2.  **Linfocitos %: 60.70%** (intervalo de referencia: 40.00 - 49.00)

    -   El valor está por encima del rango normal.

3.  **Monocitos %: 4.60%** (intervalo de referencia: 1.00 - 5.00)

    -   El valor está dentro del rango normal.

4.  **Eosinófilos %: 4.10%** (intervalo de referencia: 2.70 - 3.30)

    -   El valor está por encima del rango normal.

5.  **Basófilos %: 0.50%** (intervalo de referencia: 0.60 - 0.80)

    -   El valor está por debajo del rango normal.

### **Uroanálisis:**

1.  **Densidad: 1015**

    -   La densidad está dentro del rango normal.

2.  **pH: 6.0** (rango normal: 4.8 - 7.4)

    -   El pH está dentro del rango normal.

3.  **Sedimento Urinario:**

    -   Se observa un número normal de leucocitos, bacterias escasas, y células epiteliales escasas.

En resumen, algunos resultados están fuera del rango de referencia, y se recomienda realizar un seguimiento y correlacionar estos resultados con la historia clínica y la evolución actual del niño. Es especialmente importante abordar el elevado nivel de creatin quinasa, la alta concentración de vitamina B12 y la insuficiencia de vitamina D. Se sugiere consultar con un profesional de la salud para una evaluación más detallada.
